//! `mastermind init` command handler.
//!
//! Scaffolds a project for the Mastermind workflow: creates `.mastermind/`,
//! writes CONTEXT.md (and optionally CLAUDE.md), builds the index, and
//! optionally reconciles the npm workflow bundle into `~/.claude/`.

use mmcg::indexer::Indexer;
use mmcg::store::Store;
use std::collections::BTreeSet;
#[cfg(test)]
use std::fs;
use std::path::Path;
use std::path::PathBuf;
use std::process::Command;

use crate::templates;

/// Options for [`do_init`].
pub struct InitOpts {
    /// Explicit index location from the global `--index` option.
    pub index_path: Option<PathBuf>,
    /// Overwrite an existing CONTEXT.md / CLAUDE.md.
    pub force: bool,
    /// Run `mastermind index .` immediately after scaffolding.
    pub index: bool,
    /// Auto-fill CONTEXT.md / CLAUDE.md via `claude -p`.
    pub claude: bool,
    /// Reconcile the npm workflow bundle into `~/.claude/`.
    pub global: bool,
    /// Enrich `~/.mastermind/style.md` from this repository's authored history.
    /// Re-mining is idempotent and preserves manual and interpreted sections.
    pub seed_style: bool,
}

/// Scaffold a Mastermind project at `root`.
pub fn do_init(root: &Path, opts: InitOpts) -> Result<(), Box<dyn std::error::Error>> {
    let InitOpts {
        index_path,
        force,
        index,
        claude,
        global,
        seed_style,
    } = opts;
    let mut created: Vec<String> = Vec::new();
    let mut skipped: Vec<String> = Vec::new();
    let mut warnings: Vec<String> = Vec::new();
    let mut context_fill_prompt: Option<String> = None;

    // Stack detection informs the drafting prompt, but CONTEXT stays lean and
    // stack-agnostic: commands and layout are derivable and belong in CLAUDE.md.
    let Stack {
        label: stack_label,
        warnings: stack_warnings,
    } = detect_stack(root);
    warnings.extend(stack_warnings);
    created.push(format!("auto-detected stack: {stack_label}"));

    let mastermind_dir = root.join(".mastermind");
    let tasks_dir = mastermind_dir.join("tasks");
    if mmcg::task_scaffold::ensure_repository_directory(root, &mastermind_dir)? {
        created.push(".mastermind/".into());
    } else {
        skipped.push(".mastermind/ (already exists)".into());
    }
    let local_ignore = mmcg::task_scaffold::write_project_file(
        root,
        &mastermind_dir.join(".gitignore"),
        "# Generated by `mastermind init` — local working state, not for commit.\n\
         # To share a specific file, add `!path/to/file` AFTER the `*` line below.\n\
         *\n\
         !.gitignore\n",
        false,
    )?;
    if local_ignore.written {
        created.push(".mastermind/.gitignore".into());
    } else {
        skipped.push(".mastermind/.gitignore (already exists)".into());
    }

    if mmcg::task_scaffold::ensure_repository_directory(root, &tasks_dir)? {
        created.push(".mastermind/tasks/".into());
    } else {
        skipped.push(".mastermind/tasks/ (already exists)".into());
    }

    let legacy_tasks = root.join(".tasks");
    if legacy_tasks.exists() {
        warnings.push(
            "legacy `.tasks/` directory exists at project root (pre-0.6.0 layout). \
             Migrate it with: `mv .tasks/* .mastermind/tasks/ && rmdir .tasks` \
             — specs now live under `.mastermind/tasks/`."
                .to_string(),
        );
    }

    match mmcg::task_scaffold::discover_legacy_flat_specs(root) {
        Ok(flat_specs) if !flat_specs.is_empty() => {
            let example = flat_specs.first().cloned().unwrap_or_default();
            let stem = example.strip_suffix(".md").unwrap_or(&example);
            warnings.push(format!(
                "found {n} flat spec file(s) under `.mastermind/tasks/` (0.6.x layout, e.g. `{example}`). \
                 Migrate each `NNN-name.md` to `NNN-name/spec.md`. Example: \
                 `mkdir -p .mastermind/tasks/{stem} && mv .mastermind/tasks/{example} .mastermind/tasks/{stem}/spec.md` \
                 — flat specs are no longer indexed.",
                n = flat_specs.len(),
            ));
        }
        Ok(_) => {}
        Err(error) => warnings.push(format!(
            "could not inspect legacy flat specs under `.mastermind/tasks/`: {error}"
        )),
    }

    let context_path = root.join("CONTEXT.md");
    let context_body = templates::strip_comment(templates::CONTEXT_TEMPLATE);
    let context_write =
        mmcg::task_scaffold::write_project_file(root, &context_path, &context_body, force)?;
    if let Some(backup) = &context_write.backup {
        created.push(format!(
            "preserved existing CONTEXT.md → {}",
            backup.display()
        ));
    }
    let context_created = context_write.written;
    if context_created {
        created.push(format!(
            "CONTEXT.md (lean; detected stack: {})",
            stack_label
        ));
    } else {
        skipped.push("CONTEXT.md (already exists — pass --force to overwrite)".into());
    }

    // The workflow CLAUDE.md is always dropped — it IS Mastermind (skipped only
    // if the repo already has its own CLAUDE.md, unless --force).
    let mut claude_md_created = false;
    {
        let claude_path = root.join("CLAUDE.md");
        let claude_body = templates::strip_comment(templates::WORKFLOW_TEMPLATE);
        let claude_write =
            mmcg::task_scaffold::write_project_file(root, &claude_path, &claude_body, force)?;
        if let Some(backup) = &claude_write.backup {
            created.push(format!(
                "preserved existing CLAUDE.md → {}",
                backup.display()
            ));
        }
        if claude_write.written {
            created.push("CLAUDE.md (workflow)".into());
            claude_md_created = true;
        } else {
            skipped.push("CLAUDE.md (already exists — pass --force to overwrite)".into());
        }
    }

    let obsolete_template = tasks_dir.join("_spec-template.md");
    if obsolete_template.exists() {
        warnings.push(
            "found `.mastermind/tasks/_spec-template.md` — obsolete (the planner skill \
             uses its own bundled template, this copy is unused). \
             Safe to remove: `rm .mastermind/tasks/_spec-template.md`."
                .to_string(),
        );
    }

    let db_path = index_path.unwrap_or_else(|| mastermind_dir.join("mmcg.db"));
    if !db_path.exists() {
        let _ = Store::open(&db_path)?;
        created.push(".mastermind/mmcg.db".into());
    } else {
        skipped.push(".mastermind/mmcg.db (already exists)".into());
    }

    let mut index_ready = false;
    if index {
        let mut store = Store::open(&db_path)?;
        let indexer = Indexer::new(root);
        match indexer.index_all(&mut store, false) {
            Ok(stats) => {
                index_ready = true;
                // Report the index's *totals* (from the db), not just this run's
                // delta — an incremental no-op indexes 0 files but the index is
                // still fully populated, and "indexed 0 files" reads as empty.
                let files = store.file_count().unwrap_or(stats.files_indexed);
                let symbols = store.symbol_count().unwrap_or(stats.symbols_total);
                if stats.files_indexed == 0 {
                    created.push(format!(
                        "index up to date — {files} files, {symbols} symbols (0 reindexed, {} ms)",
                        stats.duration_ms
                    ));
                } else {
                    created.push(format!(
                        "indexed {} files, {symbols} symbols total ({} ms)",
                        stats.files_indexed, stats.duration_ms
                    ));
                }
            }
            Err(e) => warnings.push(format!(
                "index build failed: {e} — run `mastermind index .` manually"
            )),
        }
    } else {
        skipped.push("index build (--no-index) — run `mastermind index .` when ready".into());
    }

    let fill_context = claude && context_created;
    let fill_claude_md = claude && claude_md_created;
    if fill_context || fill_claude_md {
        let claude_md_path = root.join("CLAUDE.md");
        let prompt = draft_prompt(
            fill_context.then_some(context_path.as_path()),
            fill_claude_md.then_some(claude_md_path.as_path()),
        );
        match run_claude_draft(root, &prompt) {
            Ok(()) => {
                if fill_context {
                    created.push("CONTEXT.md populated via `claude -p`".into());
                }
                if fill_claude_md {
                    created.push("CLAUDE.md placeholders filled via `claude -p`".into());
                }
                if index_ready {
                    match refresh_project_history(root, &db_path) {
                        Ok(indexed) => created.push(format!(
                            "refreshed {indexed} durable history artifact(s) after scaffold drafting"
                        )),
                        Err(error) => warnings.push(format!(
                            "post-draft history refresh failed: {error} — run `mastermind index .`"
                        )),
                    }
                }
            }
            Err(e) => {
                warnings.push(format!("claude -p auto-fill skipped: {e}"));
                context_fill_prompt = Some(prompt);
            }
        }
    }

    if global {
        match install_workflow_global() {
            Ok(msg) => created.push(msg),
            Err(e) => warnings.push(format!("global workflow install skipped — {e}")),
        }
    }

    if seed_style {
        match mmcg::miner::profile::mine(root, None, false, false) {
            Ok(mmcg::miner::profile::SeedOutcome::Enriched {
                author,
                repo_commits,
                repos,
                rules,
                ..
            }) => created.push(format!(
                "~/.mastermind/style.md — as `{author}` ({rules} rule(s), {repos} repo(s), \
                 +{repo_commits} commits here)"
            )),
            Ok(mmcg::miner::profile::SeedOutcome::NoCommits { .. }) => {
                skipped.push("~/.mastermind/style.md (no commits by you in this repo yet)".into())
            }
            Err(e) => warnings.push(format!("style profile seed skipped — {e}")),
        }
    }

    println!("Mastermind workflow initialized at {}", root.display());
    if !created.is_empty() {
        println!("\nCreated:");
        for c in &created {
            println!("  + {c}");
        }
    }
    if !warnings.is_empty() {
        println!("\nWarnings:");
        for w in &warnings {
            println!("  ! {w}");
        }
    }
    if !skipped.is_empty() {
        println!("\nSkipped:");
        for s in &skipped {
            println!("  - {s}");
        }
    }

    println!("\nNext steps:");
    println!("  1. Register with Claude Code:  mastermind setup claude --write");
    println!("     (run once — the global server serves whichever project you open)");
    println!("  2. Add `.mastermind/` to your project's root `.gitignore` (local working state)");
    println!("  3. (Optional) Keep the index fresh in another terminal:  mastermind watch");
    if claude {
        println!(
            "  4. Review the drafted CLAUDE.md — placeholders were filled from your codebase."
        );
    } else {
        println!("  4. Fill CLAUDE.md's <PLACEHOLDER> sections (--no-claude skipped auto-fill).");
    }
    println!(
        "  5. (Optional) richer \"write like me\" profile: run /mastermind-style-deep in Claude Code"
    );
    if let Some(prompt) = context_fill_prompt {
        println!(
            "\nScaffold files were left as templates. To fill them, paste this into Claude Code:\n\n  {prompt}"
        );
    }

    Ok(())
}

fn refresh_project_history(root: &Path, db_path: &Path) -> Result<u32, String> {
    let mut store = Store::open(db_path).map_err(|error| error.to_string())?;
    Indexer::new(root)
        .index_project_history(&mut store)
        .map(|stats| stats.indexed)
        .map_err(|error| error.to_string())
}

/// A detected stack: a rich human label (`node (react)`, `python (django)`,
/// `rust`) plus the lean CONTEXT.md template to scaffold (bespoke where we ship
/// one, else the generic scaffold).
struct Stack {
    label: String,
    warnings: Vec<String>,
}

impl Stack {
    fn new(label: impl Into<String>, warnings: Vec<String>) -> Self {
        Stack {
            label: label.into(),
            warnings,
        }
    }
}

const STACK_MANIFEST_LIMIT: u64 = 1024 * 1024;

struct StackManifest {
    name: &'static str,
    contents: Option<String>,
    error: Option<String>,
}

impl StackManifest {
    fn present(&self) -> bool {
        self.contents.is_some() || self.error.is_some()
    }

    fn warning(&self) -> Option<String> {
        self.error.as_ref().map(|error| {
            format!(
                "stack detection ignored unsafe or unreadable `{}`: {error}",
                self.name
            )
        })
    }
}

fn read_stack_manifest(root: &Path, name: &'static str) -> StackManifest {
    match mmcg::bounded_fs::read_optional_repository_text(
        root,
        Path::new(name),
        STACK_MANIFEST_LIMIT,
    ) {
        Ok(Some(contents)) => StackManifest {
            name,
            contents: Some(contents),
            error: None,
        },
        Ok(None) => StackManifest {
            name,
            contents: None,
            error: None,
        },
        Err(error) => StackManifest {
            name,
            contents: None,
            error: Some(error.to_string()),
        },
    }
}

fn dependency_name(value: &str) -> String {
    value.trim().to_ascii_lowercase().replace(['_', '.'], "-")
}

fn node_dependencies(contents: &str) -> Result<BTreeSet<String>, String> {
    let package: serde_json::Value =
        serde_json::from_str(contents).map_err(|error| error.to_string())?;
    let package = package
        .as_object()
        .ok_or_else(|| "top-level value is not an object".to_string())?;
    let mut dependencies = BTreeSet::new();
    for section in [
        "dependencies",
        "devDependencies",
        "peerDependencies",
        "optionalDependencies",
    ] {
        let Some(value) = package.get(section) else {
            continue;
        };
        let entries = value
            .as_object()
            .ok_or_else(|| format!("`{section}` is not an object"))?;
        dependencies.extend(entries.keys().map(|name| name.to_ascii_lowercase()));
    }
    Ok(dependencies)
}

fn cargo_dependency_table(value: Option<&toml::Value>, dependencies: &mut BTreeSet<String>) {
    let Some(table) = value.and_then(toml::Value::as_table) else {
        return;
    };
    for (alias, specification) in table {
        dependencies.insert(dependency_name(alias));
        if let Some(package) = specification
            .as_table()
            .and_then(|value| value.get("package"))
            .and_then(toml::Value::as_str)
        {
            dependencies.insert(dependency_name(package));
        }
    }
}

fn cargo_dependencies(contents: &str) -> Result<BTreeSet<String>, String> {
    let manifest: toml::Value = toml::from_str(contents).map_err(|error| error.to_string())?;
    let root = manifest
        .as_table()
        .ok_or_else(|| "top-level value is not a table".to_string())?;
    let mut dependencies = BTreeSet::new();
    for section in ["dependencies", "dev-dependencies", "build-dependencies"] {
        cargo_dependency_table(root.get(section), &mut dependencies);
    }
    if let Some(workspace) = root.get("workspace").and_then(toml::Value::as_table) {
        cargo_dependency_table(workspace.get("dependencies"), &mut dependencies);
    }
    if let Some(targets) = root.get("target").and_then(toml::Value::as_table) {
        for target in targets.values().filter_map(toml::Value::as_table) {
            for section in ["dependencies", "dev-dependencies", "build-dependencies"] {
                cargo_dependency_table(target.get(section), &mut dependencies);
            }
        }
    }
    Ok(dependencies)
}

fn python_requirement_name(requirement: &str) -> Option<String> {
    let requirement = requirement.trim_start();
    if requirement.is_empty()
        || requirement.starts_with('#')
        || requirement.starts_with('-')
        || !requirement
            .as_bytes()
            .first()
            .is_some_and(u8::is_ascii_alphanumeric)
    {
        return None;
    }
    let name = requirement
        .chars()
        .take_while(|character| {
            character.is_ascii_alphanumeric() || matches!(character, '-' | '_' | '.')
        })
        .collect::<String>();
    (!name.is_empty()).then(|| dependency_name(&name))
}

fn add_python_requirement_array(value: Option<&toml::Value>, dependencies: &mut BTreeSet<String>) {
    let Some(requirements) = value.and_then(toml::Value::as_array) else {
        return;
    };
    dependencies.extend(
        requirements
            .iter()
            .filter_map(toml::Value::as_str)
            .filter_map(python_requirement_name),
    );
}

fn add_python_dependency_table(value: Option<&toml::Value>, dependencies: &mut BTreeSet<String>) {
    let Some(table) = value.and_then(toml::Value::as_table) else {
        return;
    };
    dependencies.extend(table.keys().map(|name| dependency_name(name)));
}

fn pyproject_dependencies(contents: &str) -> Result<BTreeSet<String>, String> {
    let manifest: toml::Value = toml::from_str(contents).map_err(|error| error.to_string())?;
    let root = manifest
        .as_table()
        .ok_or_else(|| "top-level value is not a table".to_string())?;
    let mut dependencies = BTreeSet::new();
    if let Some(project) = root.get("project").and_then(toml::Value::as_table) {
        add_python_requirement_array(project.get("dependencies"), &mut dependencies);
        if let Some(optional) = project
            .get("optional-dependencies")
            .and_then(toml::Value::as_table)
        {
            for group in optional.values() {
                add_python_requirement_array(Some(group), &mut dependencies);
            }
        }
    }
    if let Some(groups) = root
        .get("dependency-groups")
        .and_then(toml::Value::as_table)
    {
        for group in groups.values() {
            add_python_requirement_array(Some(group), &mut dependencies);
        }
    }
    if let Some(tool) = root.get("tool").and_then(toml::Value::as_table) {
        if let Some(poetry) = tool.get("poetry").and_then(toml::Value::as_table) {
            add_python_dependency_table(poetry.get("dependencies"), &mut dependencies);
            add_python_dependency_table(poetry.get("dev-dependencies"), &mut dependencies);
            if let Some(groups) = poetry.get("group").and_then(toml::Value::as_table) {
                for group in groups.values().filter_map(toml::Value::as_table) {
                    add_python_dependency_table(group.get("dependencies"), &mut dependencies);
                }
            }
        }
        if let Some(uv) = tool.get("uv").and_then(toml::Value::as_table) {
            add_python_requirement_array(uv.get("dev-dependencies"), &mut dependencies);
        }
    }
    Ok(dependencies)
}

fn pipfile_dependencies(contents: &str) -> Result<BTreeSet<String>, String> {
    let manifest: toml::Value = toml::from_str(contents).map_err(|error| error.to_string())?;
    let root = manifest
        .as_table()
        .ok_or_else(|| "top-level value is not a table".to_string())?;
    let mut dependencies = BTreeSet::new();
    for section in ["packages", "dev-packages"] {
        add_python_dependency_table(root.get(section), &mut dependencies);
    }
    Ok(dependencies)
}

fn add_manifest_parse_warning(warnings: &mut Vec<String>, name: &str, error: String) {
    warnings.push(format!(
        "stack detection could not parse `{name}` dependencies: {error}"
    ));
}

/// Auto-detect the stack as runtime + framework by sniffing the repo's
/// manifests. Order matters: most-specific runtime first (Rust/Node/Python/Go),
/// and within Node, mobile and framework wrappers (React Native, Next, Nuxt)
/// before the bare runtime.
fn detect_stack(root: &Path) -> Stack {
    let cargo = read_stack_manifest(root, "Cargo.toml");
    let package = read_stack_manifest(root, "package.json");
    let pyproject = read_stack_manifest(root, "pyproject.toml");
    let requirements = read_stack_manifest(root, "requirements.txt");
    let pipfile = read_stack_manifest(root, "Pipfile");
    let setup_py = read_stack_manifest(root, "setup.py");
    let go_mod = read_stack_manifest(root, "go.mod");
    let composer = read_stack_manifest(root, "composer.json");
    let pom = read_stack_manifest(root, "pom.xml");
    let gradle = read_stack_manifest(root, "build.gradle");
    let manifests = [
        &cargo,
        &package,
        &pyproject,
        &requirements,
        &pipfile,
        &setup_py,
        &go_mod,
        &composer,
        &pom,
        &gradle,
    ];
    let mut warnings = manifests
        .iter()
        .filter_map(|manifest| manifest.warning())
        .collect::<Vec<_>>();

    if let Some(contents) = cargo.contents.as_deref() {
        let dependencies = match cargo_dependencies(contents) {
            Ok(dependencies) => dependencies,
            Err(error) => {
                add_manifest_parse_warning(&mut warnings, cargo.name, error);
                BTreeSet::new()
            }
        };
        if dependencies.contains("tauri") {
            return Stack::new("rust (tauri desktop)", warnings);
        }
        return Stack::new("rust", warnings);
    }

    if let Some(contents) = package.contents.as_deref() {
        let dependencies = match node_dependencies(contents) {
            Ok(dependencies) => dependencies,
            Err(error) => {
                add_manifest_parse_warning(&mut warnings, package.name, error);
                BTreeSet::new()
            }
        };
        if dependencies.contains("react-native") || dependencies.contains("expo") {
            return Stack::new("react native", warnings);
        }
        if dependencies.contains("electron") {
            return Stack::new("node (electron desktop)", warnings);
        }
        // Frameworks, most-specific first (Next wraps React, Nuxt wraps Vue).
        let frontend = if dependencies.contains("next") {
            Some("next.js")
        } else if dependencies.contains("nuxt") {
            Some("nuxt")
        } else if dependencies.contains("@angular/core") {
            Some("angular")
        } else if dependencies.contains("svelte") {
            Some("svelte")
        } else if dependencies.contains("vue") {
            Some("vue")
        } else if dependencies.contains("react") {
            Some("react")
        } else {
            None
        };
        if let Some(fw) = frontend {
            return Stack::new(format!("node ({fw})"), warnings);
        }
        let api = [
            "express",
            "fastify",
            "@nestjs/core",
            "koa",
            "graphql",
            "apollo-server",
            "@apollo/server",
            "hapi",
            "@hapi/hapi",
        ];
        if api.iter().any(|name| dependencies.contains(*name)) {
            return Stack::new("node (api)", warnings);
        }
        return Stack::new("node", warnings);
    }

    let python = [&pyproject, &requirements, &pipfile, &setup_py];
    if python.iter().any(|manifest| manifest.contents.is_some()) {
        let mut dependencies = BTreeSet::new();
        if let Some(contents) = pyproject.contents.as_deref() {
            match pyproject_dependencies(contents) {
                Ok(found) => dependencies.extend(found),
                Err(error) => add_manifest_parse_warning(&mut warnings, pyproject.name, error),
            }
        }
        if let Some(contents) = requirements.contents.as_deref() {
            dependencies.extend(contents.lines().filter_map(python_requirement_name));
        }
        if let Some(contents) = pipfile.contents.as_deref() {
            match pipfile_dependencies(contents) {
                Ok(found) => dependencies.extend(found),
                Err(error) => add_manifest_parse_warning(&mut warnings, pipfile.name, error),
            }
        }
        if dependencies.contains("fastapi") {
            return Stack::new("python (fastapi)", warnings);
        }
        if dependencies.contains("django") {
            return Stack::new("python (django)", warnings);
        }
        if dependencies.contains("flask") {
            return Stack::new("python (flask)", warnings);
        }
        return Stack::new("python", warnings);
    }

    if go_mod.contents.is_some() {
        return Stack::new("go", warnings);
    }

    if !manifests.iter().any(|manifest| manifest.present()) {
        match monorepo_ecosystems(root) {
            Ok(ecosystems) if ecosystems.len() >= 2 => {
                return Stack::new(format!("monorepo ({})", ecosystems.join(", ")), warnings);
            }
            Ok(_) => {}
            Err(error) => warnings.push(format!(
                "stack detection could not inspect tracked nested manifests: {error}"
            )),
        }
    }

    Stack::new("generic", warnings)
}

/// Distinct language ecosystems whose manifest lives in a *subdirectory*, via
/// `git ls-files` (tracked files only). Existence probes discard stdout, so a
/// repository with many packages cannot make `init` retain an unbounded path
/// listing. Empty when `root` isn't a Git repository.
fn monorepo_ecosystems(root: &Path) -> Result<Vec<&'static str>, String> {
    let manifest_groups: &[(&str, &[&str])] = &[
        ("javascript", &["*/package.json"]),
        ("rust", &["*/Cargo.toml"]),
        ("python", &["*/pyproject.toml", "*/requirements.txt"]),
        ("go", &["*/go.mod"]),
        ("php", &["*/composer.json"]),
        ("java", &["*/pom.xml", "*/build.gradle"]),
    ];
    let probes = manifest_groups
        .iter()
        .flat_map(|(ecosystem, pathspecs)| {
            pathspecs
                .iter()
                .map(move |pathspec| (*ecosystem, *pathspec))
        })
        .collect::<Vec<_>>();
    let pathspecs = probes
        .iter()
        .map(|(_, pathspec)| *pathspec)
        .collect::<Vec<_>>();
    let presence = mmcg::diff::tracked_pathspec_presence(root, &pathspecs)
        .map_err(|error| error.to_string())?;
    let mut ecosystems = BTreeSet::new();
    for ((ecosystem, _), present) in probes.into_iter().zip(presence) {
        if present {
            ecosystems.insert(ecosystem);
        }
    }
    Ok(ecosystems.into_iter().collect())
}

fn draft_prompt(context: Option<&Path>, claude_md: Option<&Path>) -> String {
    let mut s = String::from(
        "Fill in the following freshly-scaffolded Mastermind files for THIS project by reading the \
         codebase (use the mmcg MCP tools and file access). State only things that are true about the \
         project and not trivially derivable; do not invent.",
    );
    if let Some(p) = context {
        s.push_str(&format!(
            "\n- `{}`: verify and fill Identity and Active goals. The detected stack is only a \
             discovery hint, not durable context. Leave Decision log, \
             Known gotchas, Domain glossary, External dependencies, and Don't-touch list empty — those \
             accumulate only after semantic review.",
            p.display()
        ));
    }
    if let Some(p) = claude_md {
        s.push_str(&format!(
            "\n- `{}`: replace the <PLACEHOLDER> tokens (project name, and the run / test / typecheck / \
             lint commands) with the project's real values, inferred from package manifests, scripts, and \
             config. Leave the workflow instructions intact — only fill the placeholders.",
            p.display()
        ));
    }
    s
}

fn run_claude_draft(root: &Path, prompt: &str) -> Result<(), String> {
    println!("\nDrafting scaffold files via `claude -p` (pass --no-claude to skip)...\n");
    let claude = mmcg::setup::resolve_native_cli("claude", root)
        .map_err(|error| format!("resolve claude: {error}"))?;
    let status = std::process::Command::new(claude)
        .arg("-p")
        .arg(prompt)
        .arg("--permission-mode")
        .arg("acceptEdits")
        .current_dir(root)
        .stdin(std::process::Stdio::null())
        .status()
        .map_err(|e| {
            format!("spawn claude: {e} — is the Claude Code CLI installed and on PATH?")
        })?;
    if !status.success() {
        return Err(format!("claude exited with {status}"));
    }
    Ok(())
}

fn install_workflow_global() -> Result<String, String> {
    let installer = std::env::var("MASTERMIND_INSTALLER_JS")
        .ok()
        .filter(|s| !s.is_empty())
        .ok_or_else(|| {
            "no workflow bundle (a cargo install ships only the mmcg binary) — \
             install via npm for the full workflow: \
             `npm install -g @xcraftmind/mastermind`"
                .to_string()
        })?;
    let node = std::env::var("MASTERMIND_NODE")
        .ok()
        .filter(|s| !s.is_empty())
        .ok_or_else(|| "npm wrapper did not provide the Node.js executable".to_string())?;
    let status = Command::new(node)
        .arg(installer)
        .arg("update")
        .arg("--client")
        .arg("claude")
        .status()
        .map_err(|e| format!("spawn workflow installer: {e}"))?;
    if !status.success() {
        return Err(format!("workflow installer exited with {status}"));
    }
    Ok("reconciled the Claude workflow bundle and ownership manifest".into())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn detect_stack_empty_is_generic() {
        let d = tempfile::tempdir().unwrap();
        let s = detect_stack(d.path());
        assert_eq!(s.label, "generic");
    }

    #[test]
    fn detect_stack_rust_and_tauri() {
        let d = tempfile::tempdir().unwrap();
        fs::write(d.path().join("Cargo.toml"), "[package]\nname = \"x\"").unwrap();
        let s = detect_stack(d.path());
        assert_eq!(s.label, "rust");

        let d2 = tempfile::tempdir().unwrap();
        fs::write(
            d2.path().join("Cargo.toml"),
            "[dependencies]\ntauri = \"2\"",
        )
        .unwrap();
        assert_eq!(detect_stack(d2.path()).label, "rust (tauri desktop)");
    }

    #[test]
    fn detect_stack_uses_cargo_dependency_keys_instead_of_free_text() {
        let d = tempfile::tempdir().unwrap();
        fs::write(
            d.path().join("Cargo.toml"),
            "[package]\nname = \"tauri-migration-notes\"\ndescription = \"remove tauri\"\n\
             [dependencies]\nserde = \"1\"\n",
        )
        .unwrap();

        assert_eq!(detect_stack(d.path()).label, "rust");
    }

    #[test]
    fn detect_stack_react_native_wins_over_frameworks() {
        let d = tempfile::tempdir().unwrap();
        // RN repo that also carries react + express — RN must win.
        fs::write(
            d.path().join("package.json"),
            r#"{"dependencies":{"react-native":"0.74","react":"18","express":"4"}}"#,
        )
        .unwrap();
        assert_eq!(detect_stack(d.path()).label, "react native");
    }

    #[test]
    fn detect_stack_node_frameworks() {
        for (deps, want) in [
            (r#"{"dependencies":{"react":"18"}}"#, "node (react)"),
            (r#"{"dependencies":{"vue":"3"}}"#, "node (vue)"),
            (
                r#"{"dependencies":{"next":"14","react":"18"}}"#,
                "node (next.js)",
            ),
            (r#"{"dependencies":{"express":"4"}}"#, "node (api)"),
            (r#"{"dependencies":{"lodash":"4"}}"#, "node"),
        ] {
            let d = tempfile::tempdir().unwrap();
            fs::write(d.path().join("package.json"), deps).unwrap();
            assert_eq!(detect_stack(d.path()).label, want, "deps={deps}");
        }
        // A backend API maps to the bespoke TypeScript-API template.
        let d = tempfile::tempdir().unwrap();
        fs::write(
            d.path().join("package.json"),
            r#"{"dependencies":{"fastify":"4"}}"#,
        )
        .unwrap();
        assert_eq!(detect_stack(d.path()).label, "node (api)");
    }

    #[test]
    fn detect_stack_uses_node_dependency_sections_instead_of_free_text() {
        let d = tempfile::tempdir().unwrap();
        fs::write(
            d.path().join("package.json"),
            r#"{"description":"react and express migration","keywords":["next"],"dependencies":{"lodash":"4"}}"#,
        )
        .unwrap();
        assert_eq!(detect_stack(d.path()).label, "node");

        let malformed = tempfile::tempdir().unwrap();
        fs::write(malformed.path().join("package.json"), "{ not json").unwrap();
        let stack = detect_stack(malformed.path());
        assert_eq!(stack.label, "node");
        assert_eq!(stack.warnings.len(), 1);
        assert!(stack.warnings[0].contains("could not parse `package.json`"));
    }

    #[test]
    fn detect_stack_python_frameworks() {
        for (req, want) in [
            ("fastapi==0.110\nuvicorn", "python (fastapi)"),
            ("django==5.0", "python (django)"),
            ("flask==3", "python (flask)"),
            ("requests==2", "python"),
        ] {
            let d = tempfile::tempdir().unwrap();
            fs::write(d.path().join("requirements.txt"), req).unwrap();
            let s = detect_stack(d.path());
            assert_eq!(s.label, want);
        }

        let d = tempfile::tempdir().unwrap();
        fs::write(
            d.path().join("requirements.txt"),
            "django-filter==24.3\nflask-login==0.6\n",
        )
        .unwrap();
        assert_eq!(detect_stack(d.path()).label, "python");

        let d = tempfile::tempdir().unwrap();
        fs::write(
            d.path().join("pyproject.toml"),
            "[project]\nname = \"api\"\ndependencies = [\"FastAPI[standard]>=0.110\"]\n",
        )
        .unwrap();
        assert_eq!(detect_stack(d.path()).label, "python (fastapi)");
    }

    #[test]
    fn detect_stack_go() {
        let d = tempfile::tempdir().unwrap();
        fs::write(d.path().join("go.mod"), "module x\n\ngo 1.22").unwrap();
        let s = detect_stack(d.path());
        assert_eq!(s.label, "go");
    }

    #[cfg(unix)]
    #[test]
    fn detect_stack_does_not_read_a_symlinked_manifest() {
        use std::os::unix::fs::symlink;

        let root = tempfile::tempdir().unwrap();
        let outside = tempfile::tempdir().unwrap();
        let manifest = outside.path().join("package.json");
        fs::write(&manifest, r#"{"dependencies":{"react":"18"}}"#).unwrap();
        symlink(&manifest, root.path().join("package.json")).unwrap();

        let stack = detect_stack(root.path());

        assert_eq!(stack.label, "generic");
        assert_eq!(stack.warnings.len(), 1);
        assert!(stack.warnings[0].contains("package.json"));
    }

    #[test]
    fn detect_stack_does_not_read_an_oversized_manifest() {
        let root = tempfile::tempdir().unwrap();
        let manifest = root.path().join("package.json");
        let file = fs::File::create(&manifest).unwrap();
        file.set_len(STACK_MANIFEST_LIMIT + 1).unwrap();
        drop(file);

        let stack = detect_stack(root.path());

        assert_eq!(stack.label, "generic");
        assert_eq!(stack.warnings.len(), 1);
        assert!(stack.warnings[0].contains("limit"));
    }

    #[test]
    fn detect_stack_polyglot_monorepo() {
        let d = tempfile::tempdir().unwrap();
        let root = d.path();
        // Bare root; manifests across 3 ecosystems live in subpackages.
        for (dir, file, body) in [
            ("services/api", "pyproject.toml", "[project]\nname=\"api\""),
            ("web", "package.json", "{}"),
            ("cmd/sync", "go.mod", "module x"),
        ] {
            let p = root.join(dir);
            fs::create_dir_all(&p).unwrap();
            fs::write(p.join(file), body).unwrap();
        }
        // `git ls-files` only sees tracked files, so init + add the tree.
        for args in [["init", "-q"].as_slice(), ["add", "-A"].as_slice()] {
            Command::new("git")
                .arg("-C")
                .arg(root)
                .args(args)
                .output()
                .unwrap();
        }
        let s = detect_stack(root);
        assert_eq!(s.label, "monorepo (go, javascript, python)");
    }

    #[test]
    fn detect_stack_single_nested_ecosystem_is_generic() {
        let d = tempfile::tempdir().unwrap();
        let root = d.path();
        // One nested ecosystem only — not enough to call it a polyglot monorepo.
        fs::create_dir_all(root.join("web")).unwrap();
        fs::write(root.join("web/package.json"), "{}").unwrap();
        for args in [["init", "-q"].as_slice(), ["add", "-A"].as_slice()] {
            Command::new("git")
                .arg("-C")
                .arg(root)
                .args(args)
                .output()
                .unwrap();
        }
        assert_eq!(detect_stack(root).label, "generic");
    }

    #[test]
    fn forced_context_overwrite_can_preserve_multiple_backups() {
        let dir = tempfile::tempdir().unwrap();
        let context = dir.path().join("CONTEXT.md");
        fs::write(&context, "first\n").unwrap();
        let first = mmcg::task_scaffold::write_project_file(dir.path(), &context, "second\n", true)
            .unwrap()
            .backup
            .unwrap();
        let second = mmcg::task_scaffold::write_project_file(dir.path(), &context, "third\n", true)
            .unwrap()
            .backup
            .unwrap();
        assert_ne!(first, second);
        assert_eq!(fs::read_to_string(first).unwrap(), "first\n");
        assert_eq!(fs::read_to_string(second).unwrap(), "second\n");
        assert_eq!(fs::read_to_string(context).unwrap(), "third\n");
    }

    #[test]
    fn post_draft_history_refresh_replaces_the_pre_draft_context() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        let db = root.join(".mastermind/mmcg.db");
        fs::write(root.join("CONTEXT.md"), "initial scaffold wording\n").unwrap();
        refresh_project_history(root, &db).unwrap();

        fs::write(
            root.join("CONTEXT.md"),
            "authoritative post draft architecture\n",
        )
        .unwrap();
        refresh_project_history(root, &db).unwrap();

        let store = Store::open(&db).unwrap();
        assert!(store
            .search_project_history("authoritative", Some("context"), 10)
            .unwrap()
            .iter()
            .any(|entry| entry.path == "CONTEXT.md"));
        assert!(store
            .search_project_history("initial", Some("context"), 10)
            .unwrap()
            .is_empty());
    }

    #[test]
    fn post_draft_history_refresh_rejects_an_index_from_another_repository() {
        let indexed = tempfile::tempdir().unwrap();
        let indexed_root = indexed.path();
        fs::write(
            indexed_root.join("CONTEXT.md"),
            "foreign source history marker\n",
        )
        .unwrap();
        let db = indexed_root.join("mmcg.db");
        let mut store = Store::open(&db).unwrap();
        Indexer::new(indexed_root)
            .index_all(&mut store, false)
            .unwrap();
        drop(store);

        let target = tempfile::tempdir().unwrap();
        fs::write(
            target.path().join("CONTEXT.md"),
            "target replacement history marker\n",
        )
        .unwrap();

        let error = refresh_project_history(target.path(), &db).unwrap_err();
        assert!(
            error.contains("index belongs to"),
            "unexpected error: {error}"
        );

        let store = Store::open(&db).unwrap();
        assert_eq!(
            store
                .search_project_history("foreign source", Some("context"), 10)
                .unwrap()
                .len(),
            1,
            "a rejected refresh must preserve the source repository history"
        );
        assert!(store
            .search_project_history("target replacement", Some("context"), 10)
            .unwrap()
            .is_empty());
    }

    #[cfg(unix)]
    #[test]
    fn context_writes_and_backups_reject_symlinks() {
        use std::os::unix::fs::symlink;

        let dir = tempfile::tempdir().unwrap();
        let outside = dir.path().join("outside.md");
        let context = dir.path().join("CONTEXT.md");
        fs::write(&outside, "do not overwrite\n").unwrap();
        symlink(&outside, &context).unwrap();

        assert!(mmcg::task_scaffold::write_project_file(
            dir.path(),
            &context,
            "replacement\n",
            true,
        )
        .is_err());
        assert_eq!(fs::read_to_string(outside).unwrap(), "do not overwrite\n");
    }
}
