//! `mastermind init` command handler.
//!
//! Scaffolds a project for the Mastermind workflow: creates `.mastermind/`,
//! writes CONTEXT.md (and optionally CLAUDE.md), builds the index, and
//! optionally installs the workflow bundle into `~/.claude/`.

use mmcg::indexer::Indexer;
use mmcg::store::Store;
use std::fs;
use std::path::Path;

use crate::{templates, Profile};

/// Options for [`do_init`].
pub struct InitOpts {
    /// Overwrite an existing CONTEXT.md / CLAUDE.md.
    pub force: bool,
    /// Run `mastermind index .` immediately after scaffolding.
    pub index: bool,
    /// Auto-fill CONTEXT.md / CLAUDE.md via `claude -p`.
    pub claude: bool,
    /// Install the workflow bundle into `~/.claude/`.
    pub global: bool,
    /// Seed `~/.mastermind/style.md` from the author's git history, only if
    /// absent (never clobbers a hand-edited profile).
    pub seed_style: bool,
}

/// Scaffold a Mastermind project at `root`.
pub fn do_init(root: &Path, opts: InitOpts) -> Result<(), Box<dyn std::error::Error>> {
    let InitOpts {
        force,
        index,
        claude,
        global,
        seed_style,
    } = opts;
    let mut created: Vec<String> = Vec::new();
    let mut skipped: Vec<String> = Vec::new();
    let mut warnings: Vec<String> = Vec::new();
    let mut context_fill_prompt: Option<String> = None;

    // Batteries-included: auto-detect the CONTEXT.md stack profile from the repo.
    let profile = detect_stack(root);
    created.push(format!(
        "auto-detected stack: {} CONTEXT.md profile",
        templates::profile_label(profile)
    ));

    let mastermind_dir = root.join(".mastermind");
    let tasks_dir = mastermind_dir.join("tasks");
    if !mastermind_dir.exists() {
        fs::create_dir_all(&mastermind_dir)?;
        fs::write(
            mastermind_dir.join(".gitignore"),
            "# Generated by `mastermind init` — local working state, not for commit.\n\
             # To share a specific file, add `!path/to/file` AFTER the `*` line below.\n\
             *\n\
             !.gitignore\n",
        )?;
        created.push(".mastermind/.gitignore".into());
    } else {
        skipped.push(".mastermind/ (already exists)".into());
    }

    if !tasks_dir.exists() {
        fs::create_dir_all(&tasks_dir)?;
        created.push(".mastermind/tasks/".into());
    } else {
        skipped.push(".mastermind/tasks/ (already exists)".into());
    }

    let legacy_tasks = root.join(".tasks");
    if legacy_tasks.exists() {
        warnings.push(
            "legacy `.tasks/` directory exists at project root (pre-0.6.0 layout). \
             Migrate it with: `mv .tasks/* .mastermind/tasks/ && rmdir .tasks` \
             — specs now live under `.mastermind/tasks/`."
                .to_string(),
        );
    }

    let flat_specs = collect_flat_specs(&tasks_dir);
    if !flat_specs.is_empty() {
        let example = flat_specs.first().cloned().unwrap_or_default();
        let stem = example.strip_suffix(".md").unwrap_or(&example);
        warnings.push(format!(
            "found {n} flat spec file(s) under `.mastermind/tasks/` (0.6.x layout, e.g. `{example}`). \
             Migrate each `NNN-name.md` to `NNN-name/spec.md`. Example: \
             `mkdir -p .mastermind/tasks/{stem} && mv .mastermind/tasks/{example} .mastermind/tasks/{stem}/spec.md` \
             — flat specs are no longer indexed.",
            n = flat_specs.len(),
        ));
    }

    let context_path = root.join("CONTEXT.md");
    let context_body = templates::strip_comment(templates::for_profile(profile));
    let context_created = write_if_absent(&context_path, &context_body, force)?;
    if context_created {
        let label = match profile {
            Profile::Generic => "CONTEXT.md".to_string(),
            _ => format!(
                "CONTEXT.md (profile: {})",
                templates::profile_label(profile)
            ),
        };
        created.push(label);
    } else {
        skipped.push("CONTEXT.md (already exists — pass --force to overwrite)".into());
    }

    // The workflow CLAUDE.md is always dropped — it IS Mastermind (skipped only
    // if the repo already has its own CLAUDE.md, unless --force).
    let mut claude_md_created = false;
    {
        let claude_path = root.join("CLAUDE.md");
        let claude_body = templates::strip_comment(templates::WORKFLOW_TEMPLATE);
        if write_if_absent(&claude_path, &claude_body, force)? {
            created.push("CLAUDE.md (workflow)".into());
            claude_md_created = true;
        } else {
            skipped.push("CLAUDE.md (already exists — pass --force to overwrite)".into());
        }
    }

    let obsolete_template = tasks_dir.join("_spec-template.md");
    if obsolete_template.exists() {
        warnings.push(
            "found `.mastermind/tasks/_spec-template.md` — obsolete (the planner skill \
             uses its own bundled template, this copy is unused). \
             Safe to remove: `rm .mastermind/tasks/_spec-template.md`."
                .to_string(),
        );
    }

    let db_path = mastermind_dir.join("mmcg.db");
    if !db_path.exists() {
        let _ = Store::open(&db_path)?;
        created.push(".mastermind/mmcg.db".into());
    } else {
        skipped.push(".mastermind/mmcg.db (already exists)".into());
    }

    if index {
        let mut store = Store::open(&db_path)?;
        let indexer = Indexer::new(root);
        match indexer.index_all(&mut store, false) {
            Ok(stats) => {
                // Report the index's *totals* (from the db), not just this run's
                // delta — an incremental no-op indexes 0 files but the index is
                // still fully populated, and "indexed 0 files" reads as empty.
                let files = store.file_count().unwrap_or(stats.files_indexed);
                let symbols = store.symbol_count().unwrap_or(stats.symbols_total);
                if stats.files_indexed == 0 {
                    created.push(format!(
                        "index up to date — {files} files, {symbols} symbols (0 reindexed, {} ms)",
                        stats.duration_ms
                    ));
                } else {
                    created.push(format!(
                        "indexed {} files, {symbols} symbols total ({} ms)",
                        stats.files_indexed, stats.duration_ms
                    ));
                }
            }
            Err(e) => warnings.push(format!(
                "index build failed: {e} — run `mastermind index .` manually"
            )),
        }
    } else {
        skipped.push("index build (--no-index) — run `mastermind index .` when ready".into());
    }

    let fill_context = claude && context_created;
    let fill_claude_md = claude && claude_md_created;
    if fill_context || fill_claude_md {
        let claude_md_path = root.join("CLAUDE.md");
        let prompt = draft_prompt(
            fill_context.then_some(context_path.as_path()),
            fill_claude_md.then_some(claude_md_path.as_path()),
        );
        match run_claude_draft(root, &prompt) {
            Ok(()) => {
                if fill_context {
                    created.push("CONTEXT.md populated via `claude -p`".into());
                }
                if fill_claude_md {
                    created.push("CLAUDE.md placeholders filled via `claude -p`".into());
                }
            }
            Err(e) => {
                warnings.push(format!("claude -p auto-fill skipped: {e}"));
                context_fill_prompt = Some(prompt);
            }
        }
    }

    if global {
        match install_workflow_global() {
            Ok(msg) => created.push(msg),
            Err(e) => warnings.push(format!("global workflow install skipped — {e}")),
        }
    }

    if seed_style {
        match mmcg::miner::profile::mine(root, None, false, false) {
            Ok(mmcg::miner::profile::SeedOutcome::Enriched { repos, rules, .. }) => created.push(
                format!("~/.mastermind/style.md ({rules} rule(s) across {repos} repo(s))"),
            ),
            Ok(mmcg::miner::profile::SeedOutcome::NoCommits { .. }) => {
                skipped.push("~/.mastermind/style.md (no commits by you in this repo yet)".into())
            }
            Err(e) => warnings.push(format!("style profile seed skipped — {e}")),
        }
    }

    println!("Mastermind workflow initialized at {}", root.display());
    if !created.is_empty() {
        println!("\nCreated:");
        for c in &created {
            println!("  + {c}");
        }
    }
    if !warnings.is_empty() {
        println!("\nWarnings:");
        for w in &warnings {
            println!("  ! {w}");
        }
    }
    if !skipped.is_empty() {
        println!("\nSkipped:");
        for s in &skipped {
            println!("  - {s}");
        }
    }

    println!("\nNext steps:");
    println!("  1. Register with Claude Code:  mastermind setup claude --write-mcp");
    println!("     (run once — the global server serves whichever project you open)");
    println!("  2. Add `.mastermind/` to your project's root `.gitignore` (local working state)");
    println!("  3. (Optional) Keep the index fresh in another terminal:  mastermind watch");
    if claude {
        println!(
            "  4. Review the drafted CLAUDE.md — placeholders were filled from your codebase."
        );
    } else {
        println!("  4. Fill CLAUDE.md's <PLACEHOLDER> sections (--no-claude skipped auto-fill).");
    }
    if let Some(prompt) = context_fill_prompt {
        println!(
            "\nScaffold files were left as templates. To fill them, paste this into Claude Code:\n\n  {prompt}"
        );
    }

    Ok(())
}

/// Pick a CONTEXT.md stack profile by sniffing the repo's manifests. Order
/// matters: React Native repos also carry TypeScript, so check them first.
fn detect_stack(root: &Path) -> Profile {
    let exists = |name: &str| root.join(name).exists();
    let read = |name: &str| {
        fs::read_to_string(root.join(name))
            .unwrap_or_default()
            .to_ascii_lowercase()
    };

    let pkg = read("package.json");
    if pkg.contains("\"react-native\"") || pkg.contains("\"expo\"") {
        return Profile::ReactNative;
    }
    let ts_api = [
        "express", "fastify", "@nestjs", "koa", "graphql", "apollo", "hapi",
    ];
    if (exists("tsconfig.json") || pkg.contains("\"typescript\""))
        && ts_api.iter().any(|f| pkg.contains(f))
    {
        return Profile::TypescriptApi;
    }
    if read("pyproject.toml").contains("fastapi") || read("requirements.txt").contains("fastapi") {
        return Profile::PythonFastapi;
    }
    if exists("Cargo.toml") && (read("Cargo.toml").contains("[[bin]]") || exists("src/main.rs")) {
        return Profile::RustCli;
    }
    Profile::Generic
}

fn write_if_absent(
    path: &Path,
    contents: &str,
    force: bool,
) -> Result<bool, Box<dyn std::error::Error>> {
    if path.exists() && !force {
        return Ok(false);
    }
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(path, contents)?;
    Ok(true)
}

fn collect_flat_specs(tasks_dir: &Path) -> Vec<String> {
    let Ok(entries) = fs::read_dir(tasks_dir) else {
        return Vec::new();
    };
    let mut out = Vec::new();
    for dirent in entries.flatten() {
        let path = dirent.path();
        if !path.is_file() {
            continue;
        }
        let Some(name) = path.file_name().and_then(|n| n.to_str()) else {
            continue;
        };
        if !name.ends_with(".md") || name.starts_with('_') || name.starts_with('.') {
            continue;
        }
        out.push(name.to_string());
    }
    out.sort();
    out
}

fn draft_prompt(context: Option<&Path>, claude_md: Option<&Path>) -> String {
    let mut s = String::from(
        "Fill in the following freshly-scaffolded Mastermind files for THIS project by reading the \
         codebase (use the mmcg MCP tools and file access). State only things that are true about the \
         project and not trivially derivable; do not invent.",
    );
    if let Some(p) = context {
        s.push_str(&format!(
            "\n- `{}`: fill ONLY the Identity (what it is / what it is not / primary users) and Active \
             goals sections. Leave Decision log, Known gotchas, Domain glossary, External dependencies, \
             and Don't-touch list as the empty templates — those accumulate over time.",
            p.display()
        ));
    }
    if let Some(p) = claude_md {
        s.push_str(&format!(
            "\n- `{}`: replace the <PLACEHOLDER> tokens (project name, and the run / test / typecheck / \
             lint commands) with the project's real values, inferred from package manifests, scripts, and \
             config. Leave the workflow instructions intact — only fill the placeholders.",
            p.display()
        ));
    }
    s
}

fn run_claude_draft(root: &Path, prompt: &str) -> Result<(), String> {
    println!("\nDrafting scaffold files via `claude -p` (pass --no-claude to skip)...\n");
    let status = std::process::Command::new("claude")
        .arg("-p")
        .arg(prompt)
        .arg("--permission-mode")
        .arg("acceptEdits")
        .current_dir(root)
        .stdin(std::process::Stdio::null())
        .status()
        .map_err(|e| {
            format!("spawn claude: {e} — is the Claude Code CLI installed and on PATH?")
        })?;
    if !status.success() {
        return Err(format!("claude exited with {status}"));
    }
    Ok(())
}

fn install_workflow_global() -> Result<String, String> {
    let share = std::env::var("MASTERMIND_SHARE_DIR")
        .ok()
        .filter(|s| !s.is_empty())
        .ok_or_else(|| {
            "no workflow bundle (a cargo install ships only the mmcg binary) — \
             install via npm for the full workflow: \
             `npm install -g @xcraftmind/mastermind`, or copy `agents/` and \
             `skills/` from the repo into `~/.claude/` manually"
                .to_string()
        })?;
    let share = Path::new(&share);
    let home = dirs::home_dir().ok_or_else(|| "no $HOME — cannot locate ~/.claude".to_string())?;
    let claude = home.join(".claude");
    if !claude.exists() {
        return Err(format!(
            "{} not found (is Claude Code installed?)",
            claude.display()
        ));
    }

    let mut agents = 0usize;
    let src_agents = share.join("agents");
    if src_agents.is_dir() {
        let dst = claude.join("agents");
        fs::create_dir_all(&dst).map_err(|e| format!("create {}: {e}", dst.display()))?;
        for entry in fs::read_dir(&src_agents).map_err(|e| e.to_string())? {
            let p = entry.map_err(|e| e.to_string())?.path();
            if p.extension().and_then(|x| x.to_str()) == Some("md") {
                let name = p.file_name().expect("dir entry has a name");
                fs::copy(&p, dst.join(name)).map_err(|e| format!("copy {}: {e}", p.display()))?;
                agents += 1;
            }
        }
    }

    let mut skills = 0usize;
    let src_skills = share.join("skills");
    if src_skills.is_dir() {
        let dst_root = claude.join("skills");
        for entry in fs::read_dir(&src_skills).map_err(|e| e.to_string())? {
            let p = entry.map_err(|e| e.to_string())?.path();
            if p.is_dir() {
                let name = p.file_name().expect("dir entry has a name");
                copy_dir_all(&p, &dst_root.join(name))
                    .map_err(|e| format!("copy skill {}: {e}", p.display()))?;
                skills += 1;
            }
        }
    }

    let mut commands = 0usize;
    let src_commands = share.join("commands");
    if src_commands.is_dir() {
        let dst = claude.join("commands");
        fs::create_dir_all(&dst).map_err(|e| format!("create {}: {e}", dst.display()))?;
        for entry in fs::read_dir(&src_commands).map_err(|e| e.to_string())? {
            let p = entry.map_err(|e| e.to_string())?.path();
            if p.extension().and_then(|x| x.to_str()) == Some("md") {
                let name = p.file_name().expect("dir entry has a name");
                fs::copy(&p, dst.join(name)).map_err(|e| format!("copy {}: {e}", p.display()))?;
                commands += 1;
            }
        }
    }

    Ok(format!(
        "installed {agents} subagents + {skills} skills + {commands} commands into {}",
        claude.display()
    ))
}

fn copy_dir_all(src: &Path, dst: &Path) -> std::io::Result<()> {
    fs::create_dir_all(dst)?;
    for entry in fs::read_dir(src)? {
        let entry = entry?;
        let from = entry.path();
        let to = dst.join(entry.file_name());
        if entry.file_type()?.is_dir() {
            copy_dir_all(&from, &to)?;
        } else {
            fs::copy(&from, &to)?;
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn detect_stack_empty_is_generic() {
        let d = tempfile::tempdir().unwrap();
        assert!(matches!(detect_stack(d.path()), Profile::Generic));
    }

    #[test]
    fn detect_stack_rust_cli() {
        let d = tempfile::tempdir().unwrap();
        fs::write(
            d.path().join("Cargo.toml"),
            "[package]\nname = \"x\"\n[[bin]]\nname = \"x\"",
        )
        .unwrap();
        assert!(matches!(detect_stack(d.path()), Profile::RustCli));
    }

    #[test]
    fn detect_stack_react_native_wins_over_ts_api() {
        let d = tempfile::tempdir().unwrap();
        // RN repo that also carries express + typescript — RN must win.
        fs::write(
            d.path().join("package.json"),
            r#"{"dependencies":{"react-native":"0.74","express":"4","typescript":"5"}}"#,
        )
        .unwrap();
        fs::write(d.path().join("tsconfig.json"), "{}").unwrap();
        assert!(matches!(detect_stack(d.path()), Profile::ReactNative));
    }

    #[test]
    fn detect_stack_ts_api_and_fastapi() {
        let d = tempfile::tempdir().unwrap();
        fs::write(
            d.path().join("package.json"),
            r#"{"devDependencies":{"typescript":"5"},"dependencies":{"fastify":"4"}}"#,
        )
        .unwrap();
        assert!(matches!(detect_stack(d.path()), Profile::TypescriptApi));

        let d2 = tempfile::tempdir().unwrap();
        fs::write(
            d2.path().join("requirements.txt"),
            "fastapi==0.110\nuvicorn",
        )
        .unwrap();
        assert!(matches!(detect_stack(d2.path()), Profile::PythonFastapi));
    }
}
