//! `mastermind init` command handler.
//!
//! Scaffolds a project for the Mastermind workflow: creates `.mastermind/`,
//! writes CONTEXT.md (and optionally CLAUDE.md), builds the index, and
//! optionally reconciles the npm workflow bundle into `~/.claude/`.

use mmcg::indexer::Indexer;
use mmcg::store::Store;
use std::fs;
use std::path::Path;
use std::path::PathBuf;
use std::process::Command;

use crate::templates;

/// Options for [`do_init`].
pub struct InitOpts {
    /// Explicit index location from the global `--index` option.
    pub index_path: Option<PathBuf>,
    /// Overwrite an existing CONTEXT.md / CLAUDE.md.
    pub force: bool,
    /// Run `mastermind index .` immediately after scaffolding.
    pub index: bool,
    /// Auto-fill CONTEXT.md / CLAUDE.md via `claude -p`.
    pub claude: bool,
    /// Reconcile the npm workflow bundle into `~/.claude/`.
    pub global: bool,
    /// Enrich `~/.mastermind/style.md` from this repository's authored history.
    /// Re-mining is idempotent and preserves manual and interpreted sections.
    pub seed_style: bool,
}

/// Scaffold a Mastermind project at `root`.
pub fn do_init(root: &Path, opts: InitOpts) -> Result<(), Box<dyn std::error::Error>> {
    let InitOpts {
        index_path,
        force,
        index,
        claude,
        global,
        seed_style,
    } = opts;
    let mut created: Vec<String> = Vec::new();
    let mut skipped: Vec<String> = Vec::new();
    let mut warnings: Vec<String> = Vec::new();
    let mut context_fill_prompt: Option<String> = None;

    // Stack detection informs the drafting prompt, but CONTEXT stays lean and
    // stack-agnostic: commands and layout are derivable and belong in CLAUDE.md.
    let stack = detect_stack(root);
    created.push(format!("auto-detected stack: {}", stack.label));

    let mastermind_dir = root.join(".mastermind");
    let tasks_dir = mastermind_dir.join("tasks");
    if !mastermind_dir.exists() {
        fs::create_dir_all(&mastermind_dir)?;
        fs::write(
            mastermind_dir.join(".gitignore"),
            "# Generated by `mastermind init` — local working state, not for commit.\n\
             # To share a specific file, add `!path/to/file` AFTER the `*` line below.\n\
             *\n\
             !.gitignore\n",
        )?;
        created.push(".mastermind/.gitignore".into());
    } else {
        skipped.push(".mastermind/ (already exists)".into());
    }

    if !tasks_dir.exists() {
        fs::create_dir_all(&tasks_dir)?;
        created.push(".mastermind/tasks/".into());
    } else {
        skipped.push(".mastermind/tasks/ (already exists)".into());
    }

    let legacy_tasks = root.join(".tasks");
    if legacy_tasks.exists() {
        warnings.push(
            "legacy `.tasks/` directory exists at project root (pre-0.6.0 layout). \
             Migrate it with: `mv .tasks/* .mastermind/tasks/ && rmdir .tasks` \
             — specs now live under `.mastermind/tasks/`."
                .to_string(),
        );
    }

    let flat_specs = collect_flat_specs(&tasks_dir);
    if !flat_specs.is_empty() {
        let example = flat_specs.first().cloned().unwrap_or_default();
        let stem = example.strip_suffix(".md").unwrap_or(&example);
        warnings.push(format!(
            "found {n} flat spec file(s) under `.mastermind/tasks/` (0.6.x layout, e.g. `{example}`). \
             Migrate each `NNN-name.md` to `NNN-name/spec.md`. Example: \
             `mkdir -p .mastermind/tasks/{stem} && mv .mastermind/tasks/{example} .mastermind/tasks/{stem}/spec.md` \
             — flat specs are no longer indexed.",
            n = flat_specs.len(),
        ));
    }

    let context_path = root.join("CONTEXT.md");
    let context_body = templates::strip_comment(templates::CONTEXT_TEMPLATE);
    if force && context_path.is_file() {
        let backup = backup_existing(&context_path)?;
        created.push(format!(
            "preserved existing CONTEXT.md → {}",
            backup.display()
        ));
    }
    let context_created = write_if_absent(&context_path, &context_body, force)?;
    if context_created {
        created.push(format!(
            "CONTEXT.md (lean; detected stack: {})",
            stack.label
        ));
    } else {
        skipped.push("CONTEXT.md (already exists — pass --force to overwrite)".into());
    }

    // The workflow CLAUDE.md is always dropped — it IS Mastermind (skipped only
    // if the repo already has its own CLAUDE.md, unless --force).
    let mut claude_md_created = false;
    {
        let claude_path = root.join("CLAUDE.md");
        let claude_body = templates::strip_comment(templates::WORKFLOW_TEMPLATE);
        if write_if_absent(&claude_path, &claude_body, force)? {
            created.push("CLAUDE.md (workflow)".into());
            claude_md_created = true;
        } else {
            skipped.push("CLAUDE.md (already exists — pass --force to overwrite)".into());
        }
    }

    let obsolete_template = tasks_dir.join("_spec-template.md");
    if obsolete_template.exists() {
        warnings.push(
            "found `.mastermind/tasks/_spec-template.md` — obsolete (the planner skill \
             uses its own bundled template, this copy is unused). \
             Safe to remove: `rm .mastermind/tasks/_spec-template.md`."
                .to_string(),
        );
    }

    let db_path = index_path.unwrap_or_else(|| mastermind_dir.join("mmcg.db"));
    if !db_path.exists() {
        let _ = Store::open(&db_path)?;
        created.push(".mastermind/mmcg.db".into());
    } else {
        skipped.push(".mastermind/mmcg.db (already exists)".into());
    }

    let mut index_ready = false;
    if index {
        let mut store = Store::open(&db_path)?;
        let indexer = Indexer::new(root);
        match indexer.index_all(&mut store, false) {
            Ok(stats) => {
                index_ready = true;
                // Report the index's *totals* (from the db), not just this run's
                // delta — an incremental no-op indexes 0 files but the index is
                // still fully populated, and "indexed 0 files" reads as empty.
                let files = store.file_count().unwrap_or(stats.files_indexed);
                let symbols = store.symbol_count().unwrap_or(stats.symbols_total);
                if stats.files_indexed == 0 {
                    created.push(format!(
                        "index up to date — {files} files, {symbols} symbols (0 reindexed, {} ms)",
                        stats.duration_ms
                    ));
                } else {
                    created.push(format!(
                        "indexed {} files, {symbols} symbols total ({} ms)",
                        stats.files_indexed, stats.duration_ms
                    ));
                }
            }
            Err(e) => warnings.push(format!(
                "index build failed: {e} — run `mastermind index .` manually"
            )),
        }
    } else {
        skipped.push("index build (--no-index) — run `mastermind index .` when ready".into());
    }

    let fill_context = claude && context_created;
    let fill_claude_md = claude && claude_md_created;
    if fill_context || fill_claude_md {
        let claude_md_path = root.join("CLAUDE.md");
        let prompt = draft_prompt(
            fill_context.then_some(context_path.as_path()),
            fill_claude_md.then_some(claude_md_path.as_path()),
        );
        match run_claude_draft(root, &prompt) {
            Ok(()) => {
                if fill_context {
                    created.push("CONTEXT.md populated via `claude -p`".into());
                }
                if fill_claude_md {
                    created.push("CLAUDE.md placeholders filled via `claude -p`".into());
                }
                if index_ready {
                    match refresh_project_history(root, &db_path) {
                        Ok(indexed) => created.push(format!(
                            "refreshed {indexed} durable history artifact(s) after scaffold drafting"
                        )),
                        Err(error) => warnings.push(format!(
                            "post-draft history refresh failed: {error} — run `mastermind index .`"
                        )),
                    }
                }
            }
            Err(e) => {
                warnings.push(format!("claude -p auto-fill skipped: {e}"));
                context_fill_prompt = Some(prompt);
            }
        }
    }

    if global {
        match install_workflow_global() {
            Ok(msg) => created.push(msg),
            Err(e) => warnings.push(format!("global workflow install skipped — {e}")),
        }
    }

    if seed_style {
        match mmcg::miner::profile::mine(root, None, false, false) {
            Ok(mmcg::miner::profile::SeedOutcome::Enriched {
                author,
                repo_commits,
                repos,
                rules,
                ..
            }) => created.push(format!(
                "~/.mastermind/style.md — as `{author}` ({rules} rule(s), {repos} repo(s), \
                 +{repo_commits} commits here)"
            )),
            Ok(mmcg::miner::profile::SeedOutcome::NoCommits { .. }) => {
                skipped.push("~/.mastermind/style.md (no commits by you in this repo yet)".into())
            }
            Err(e) => warnings.push(format!("style profile seed skipped — {e}")),
        }
    }

    println!("Mastermind workflow initialized at {}", root.display());
    if !created.is_empty() {
        println!("\nCreated:");
        for c in &created {
            println!("  + {c}");
        }
    }
    if !warnings.is_empty() {
        println!("\nWarnings:");
        for w in &warnings {
            println!("  ! {w}");
        }
    }
    if !skipped.is_empty() {
        println!("\nSkipped:");
        for s in &skipped {
            println!("  - {s}");
        }
    }

    println!("\nNext steps:");
    println!("  1. Register with Claude Code:  mastermind setup claude --write");
    println!("     (run once — the global server serves whichever project you open)");
    println!("  2. Add `.mastermind/` to your project's root `.gitignore` (local working state)");
    println!("  3. (Optional) Keep the index fresh in another terminal:  mastermind watch");
    if claude {
        println!(
            "  4. Review the drafted CLAUDE.md — placeholders were filled from your codebase."
        );
    } else {
        println!("  4. Fill CLAUDE.md's <PLACEHOLDER> sections (--no-claude skipped auto-fill).");
    }
    println!(
        "  5. (Optional) richer \"write like me\" profile: run /mastermind-style-deep in Claude Code"
    );
    if let Some(prompt) = context_fill_prompt {
        println!(
            "\nScaffold files were left as templates. To fill them, paste this into Claude Code:\n\n  {prompt}"
        );
    }

    Ok(())
}

fn refresh_project_history(root: &Path, db_path: &Path) -> Result<u32, String> {
    let mut store = Store::open(db_path).map_err(|error| error.to_string())?;
    Indexer::new(root)
        .index_project_history(&mut store)
        .map(|stats| stats.indexed)
        .map_err(|error| error.to_string())
}

/// A detected stack: a rich human label (`node (react)`, `python (django)`,
/// `rust`) plus the lean CONTEXT.md template to scaffold (bespoke where we ship
/// one, else the generic scaffold).
struct Stack {
    label: String,
}

impl Stack {
    fn new(label: impl Into<String>) -> Self {
        Stack {
            label: label.into(),
        }
    }
}

/// Auto-detect the stack as runtime + framework by sniffing the repo's
/// manifests. Order matters: most-specific runtime first (Rust/Node/Python/Go),
/// and within Node, mobile and framework wrappers (React Native, Next, Nuxt)
/// before the bare runtime.
fn detect_stack(root: &Path) -> Stack {
    let exists = |name: &str| root.join(name).exists();
    let read = |name: &str| {
        fs::read_to_string(root.join(name))
            .unwrap_or_default()
            .to_ascii_lowercase()
    };

    if exists("Cargo.toml") {
        if read("Cargo.toml").contains("tauri") {
            return Stack::new("rust (tauri desktop)");
        }
        return Stack::new("rust");
    }

    let pkg = read("package.json");
    if exists("package.json") {
        if pkg.contains("\"react-native\"") || pkg.contains("\"expo\"") {
            return Stack::new("react native");
        }
        if pkg.contains("\"electron\"") {
            return Stack::new("node (electron desktop)");
        }
        // Frameworks, most-specific first (Next wraps React, Nuxt wraps Vue).
        let frontend = if pkg.contains("\"next\"") {
            Some("next.js")
        } else if pkg.contains("\"nuxt\"") {
            Some("nuxt")
        } else if pkg.contains("\"@angular/core\"") {
            Some("angular")
        } else if pkg.contains("\"svelte\"") {
            Some("svelte")
        } else if pkg.contains("\"vue\"") {
            Some("vue")
        } else if pkg.contains("\"react\"") {
            Some("react")
        } else {
            None
        };
        if let Some(fw) = frontend {
            return Stack::new(format!("node ({fw})"));
        }
        let api = [
            "express", "fastify", "@nestjs", "koa", "graphql", "apollo", "hapi",
        ];
        if api.iter().any(|f| pkg.contains(f)) {
            return Stack::new("node (api)");
        }
        return Stack::new("node");
    }

    if exists("pyproject.toml")
        || exists("requirements.txt")
        || exists("Pipfile")
        || exists("setup.py")
    {
        let py = read("pyproject.toml")
            + &read("requirements.txt")
            + &read("Pipfile")
            + &read("setup.py");
        if py.contains("fastapi") {
            return Stack::new("python (fastapi)");
        }
        if py.contains("django") {
            return Stack::new("python (django)");
        }
        if py.contains("flask") {
            return Stack::new("python (flask)");
        }
        return Stack::new("python");
    }

    if exists("go.mod") {
        return Stack::new("go");
    }

    if !root_has_manifest(root) {
        let ecos = monorepo_ecosystems(root);
        if ecos.len() >= 2 {
            return Stack::new(format!("monorepo ({})", ecos.join(", ")));
        }
    }

    Stack::new("generic")
}

/// Any root-level manifest means the repo has its own stack (one package), so it
/// isn't a bare-root monorepo even when subdirectories also carry manifests.
fn root_has_manifest(root: &Path) -> bool {
    const MANIFESTS: &[&str] = &[
        "package.json",
        "Cargo.toml",
        "pyproject.toml",
        "requirements.txt",
        "go.mod",
        "composer.json",
        "pom.xml",
        "build.gradle",
    ];
    MANIFESTS.iter().any(|m| root.join(m).exists())
}

/// Distinct language ecosystems whose manifest lives in a *subdirectory*, via
/// `git ls-files` (tracked files only). Python's two manifest kinds fold to one.
/// Empty when `root` isn't a git repo. ≥2 with a bare root ⇒ polyglot monorepo.
fn monorepo_ecosystems(root: &Path) -> Vec<&'static str> {
    let out = match Command::new("git")
        .arg("-C")
        .arg(root)
        .args([
            "ls-files",
            "*/package.json",
            "*/Cargo.toml",
            "*/pyproject.toml",
            "*/requirements.txt",
            "*/go.mod",
            "*/composer.json",
            "*/pom.xml",
            "*/build.gradle",
        ])
        .output()
    {
        Ok(o) if o.status.success() => o.stdout,
        _ => return Vec::new(),
    };
    let listing = String::from_utf8_lossy(&out).to_ascii_lowercase();
    let mut ecos = std::collections::BTreeSet::new();
    for line in listing.lines() {
        if line.ends_with("/package.json") {
            ecos.insert("javascript");
        } else if line.ends_with("/cargo.toml") {
            ecos.insert("rust");
        } else if line.ends_with("/pyproject.toml") || line.ends_with("/requirements.txt") {
            ecos.insert("python");
        } else if line.ends_with("/go.mod") {
            ecos.insert("go");
        } else if line.ends_with("/composer.json") {
            ecos.insert("php");
        } else if line.ends_with("/pom.xml") || line.ends_with("/build.gradle") {
            ecos.insert("java");
        }
    }
    ecos.into_iter().collect()
}

fn write_if_absent(
    path: &Path,
    contents: &str,
    force: bool,
) -> Result<bool, Box<dyn std::error::Error>> {
    if std::fs::symlink_metadata(path).is_ok_and(|metadata| metadata.file_type().is_symlink()) {
        return Err(format!("refusing to overwrite symlink `{}`", path.display()).into());
    }
    if path.exists() && !force {
        return Ok(false);
    }
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(path, contents)?;
    Ok(true)
}

fn backup_existing(path: &Path) -> Result<std::path::PathBuf, Box<dyn std::error::Error>> {
    if std::fs::symlink_metadata(path).is_ok_and(|metadata| metadata.file_type().is_symlink()) {
        return Err(format!("refusing to back up symlink `{}`", path.display()).into());
    }
    let file_name = path
        .file_name()
        .and_then(|name| name.to_str())
        .unwrap_or("CONTEXT.md");
    let parent = path.parent().unwrap_or_else(|| Path::new("."));
    let base = parent.join(format!("{file_name}.mastermind-backup"));
    let entry_exists = |candidate: &Path| std::fs::symlink_metadata(candidate).is_ok();
    let backup = if !entry_exists(&base) {
        base
    } else {
        (1_u32..)
            .map(|suffix| parent.join(format!("{file_name}.mastermind-backup.{suffix}")))
            .find(|candidate| !entry_exists(candidate))
            .expect("backup suffix space is unbounded")
    };
    fs::copy(path, &backup)?;
    Ok(backup)
}

fn collect_flat_specs(tasks_dir: &Path) -> Vec<String> {
    let Ok(entries) = fs::read_dir(tasks_dir) else {
        return Vec::new();
    };
    let mut out = Vec::new();
    for dirent in entries.flatten() {
        let path = dirent.path();
        if !path.is_file() {
            continue;
        }
        let Some(name) = path.file_name().and_then(|n| n.to_str()) else {
            continue;
        };
        if !name.ends_with(".md") || name.starts_with('_') || name.starts_with('.') {
            continue;
        }
        out.push(name.to_string());
    }
    out.sort();
    out
}

fn draft_prompt(context: Option<&Path>, claude_md: Option<&Path>) -> String {
    let mut s = String::from(
        "Fill in the following freshly-scaffolded Mastermind files for THIS project by reading the \
         codebase (use the mmcg MCP tools and file access). State only things that are true about the \
         project and not trivially derivable; do not invent.",
    );
    if let Some(p) = context {
        s.push_str(&format!(
            "\n- `{}`: verify and fill Identity and Active goals. The detected stack is only a \
             discovery hint, not durable context. Leave Decision log, \
             Known gotchas, Domain glossary, External dependencies, and Don't-touch list empty — those \
             accumulate only after semantic review.",
            p.display()
        ));
    }
    if let Some(p) = claude_md {
        s.push_str(&format!(
            "\n- `{}`: replace the <PLACEHOLDER> tokens (project name, and the run / test / typecheck / \
             lint commands) with the project's real values, inferred from package manifests, scripts, and \
             config. Leave the workflow instructions intact — only fill the placeholders.",
            p.display()
        ));
    }
    s
}

fn run_claude_draft(root: &Path, prompt: &str) -> Result<(), String> {
    println!("\nDrafting scaffold files via `claude -p` (pass --no-claude to skip)...\n");
    let status = std::process::Command::new("claude")
        .arg("-p")
        .arg(prompt)
        .arg("--permission-mode")
        .arg("acceptEdits")
        .current_dir(root)
        .stdin(std::process::Stdio::null())
        .status()
        .map_err(|e| {
            format!("spawn claude: {e} — is the Claude Code CLI installed and on PATH?")
        })?;
    if !status.success() {
        return Err(format!("claude exited with {status}"));
    }
    Ok(())
}

fn install_workflow_global() -> Result<String, String> {
    let installer = std::env::var("MASTERMIND_INSTALLER_JS")
        .ok()
        .filter(|s| !s.is_empty())
        .ok_or_else(|| {
            "no workflow bundle (a cargo install ships only the mmcg binary) — \
             install via npm for the full workflow: \
             `npm install -g @xcraftmind/mastermind`"
                .to_string()
        })?;
    let node = std::env::var("MASTERMIND_NODE")
        .ok()
        .filter(|s| !s.is_empty())
        .ok_or_else(|| "npm wrapper did not provide the Node.js executable".to_string())?;
    let status = Command::new(node)
        .arg(installer)
        .arg("update")
        .arg("--client")
        .arg("claude")
        .status()
        .map_err(|e| format!("spawn workflow installer: {e}"))?;
    if !status.success() {
        return Err(format!("workflow installer exited with {status}"));
    }
    Ok("reconciled the Claude workflow bundle and ownership manifest".into())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn detect_stack_empty_is_generic() {
        let d = tempfile::tempdir().unwrap();
        let s = detect_stack(d.path());
        assert_eq!(s.label, "generic");
    }

    #[test]
    fn detect_stack_rust_and_tauri() {
        let d = tempfile::tempdir().unwrap();
        fs::write(d.path().join("Cargo.toml"), "[package]\nname = \"x\"").unwrap();
        let s = detect_stack(d.path());
        assert_eq!(s.label, "rust");

        let d2 = tempfile::tempdir().unwrap();
        fs::write(
            d2.path().join("Cargo.toml"),
            "[dependencies]\ntauri = \"2\"",
        )
        .unwrap();
        assert_eq!(detect_stack(d2.path()).label, "rust (tauri desktop)");
    }

    #[test]
    fn detect_stack_react_native_wins_over_frameworks() {
        let d = tempfile::tempdir().unwrap();
        // RN repo that also carries react + express — RN must win.
        fs::write(
            d.path().join("package.json"),
            r#"{"dependencies":{"react-native":"0.74","react":"18","express":"4"}}"#,
        )
        .unwrap();
        assert_eq!(detect_stack(d.path()).label, "react native");
    }

    #[test]
    fn detect_stack_node_frameworks() {
        for (deps, want) in [
            (r#"{"dependencies":{"react":"18"}}"#, "node (react)"),
            (r#"{"dependencies":{"vue":"3"}}"#, "node (vue)"),
            (
                r#"{"dependencies":{"next":"14","react":"18"}}"#,
                "node (next.js)",
            ),
            (r#"{"dependencies":{"express":"4"}}"#, "node (api)"),
            (r#"{"dependencies":{"lodash":"4"}}"#, "node"),
        ] {
            let d = tempfile::tempdir().unwrap();
            fs::write(d.path().join("package.json"), deps).unwrap();
            assert_eq!(detect_stack(d.path()).label, want, "deps={deps}");
        }
        // A backend API maps to the bespoke TypeScript-API template.
        let d = tempfile::tempdir().unwrap();
        fs::write(
            d.path().join("package.json"),
            r#"{"dependencies":{"fastify":"4"}}"#,
        )
        .unwrap();
        assert_eq!(detect_stack(d.path()).label, "node (api)");
    }

    #[test]
    fn detect_stack_python_frameworks() {
        for (req, want) in [
            ("fastapi==0.110\nuvicorn", "python (fastapi)"),
            ("django==5.0", "python (django)"),
            ("flask==3", "python (flask)"),
            ("requests==2", "python"),
        ] {
            let d = tempfile::tempdir().unwrap();
            fs::write(d.path().join("requirements.txt"), req).unwrap();
            let s = detect_stack(d.path());
            assert_eq!(s.label, want);
        }
    }

    #[test]
    fn detect_stack_go() {
        let d = tempfile::tempdir().unwrap();
        fs::write(d.path().join("go.mod"), "module x\n\ngo 1.22").unwrap();
        let s = detect_stack(d.path());
        assert_eq!(s.label, "go");
    }

    #[test]
    fn detect_stack_polyglot_monorepo() {
        let d = tempfile::tempdir().unwrap();
        let root = d.path();
        // Bare root; manifests across 3 ecosystems live in subpackages.
        for (dir, file, body) in [
            ("services/api", "pyproject.toml", "[project]\nname=\"api\""),
            ("web", "package.json", "{}"),
            ("cmd/sync", "go.mod", "module x"),
        ] {
            let p = root.join(dir);
            fs::create_dir_all(&p).unwrap();
            fs::write(p.join(file), body).unwrap();
        }
        // `git ls-files` only sees tracked files, so init + add the tree.
        for args in [["init", "-q"].as_slice(), ["add", "-A"].as_slice()] {
            Command::new("git")
                .arg("-C")
                .arg(root)
                .args(args)
                .output()
                .unwrap();
        }
        let s = detect_stack(root);
        assert_eq!(s.label, "monorepo (go, javascript, python)");
    }

    #[test]
    fn detect_stack_single_nested_ecosystem_is_generic() {
        let d = tempfile::tempdir().unwrap();
        let root = d.path();
        // One nested ecosystem only — not enough to call it a polyglot monorepo.
        fs::create_dir_all(root.join("web")).unwrap();
        fs::write(root.join("web/package.json"), "{}").unwrap();
        for args in [["init", "-q"].as_slice(), ["add", "-A"].as_slice()] {
            Command::new("git")
                .arg("-C")
                .arg(root)
                .args(args)
                .output()
                .unwrap();
        }
        assert_eq!(detect_stack(root).label, "generic");
    }

    #[test]
    fn forced_context_overwrite_can_preserve_multiple_backups() {
        let dir = tempfile::tempdir().unwrap();
        let context = dir.path().join("CONTEXT.md");
        fs::write(&context, "first\n").unwrap();
        let first = backup_existing(&context).unwrap();
        fs::write(&context, "second\n").unwrap();
        let second = backup_existing(&context).unwrap();
        assert_ne!(first, second);
        assert_eq!(fs::read_to_string(first).unwrap(), "first\n");
        assert_eq!(fs::read_to_string(second).unwrap(), "second\n");
    }

    #[test]
    fn post_draft_history_refresh_replaces_the_pre_draft_context() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        let db = root.join(".mastermind/mmcg.db");
        fs::write(root.join("CONTEXT.md"), "initial scaffold wording\n").unwrap();
        refresh_project_history(root, &db).unwrap();

        fs::write(
            root.join("CONTEXT.md"),
            "authoritative post draft architecture\n",
        )
        .unwrap();
        refresh_project_history(root, &db).unwrap();

        let store = Store::open(&db).unwrap();
        assert!(store
            .search_project_history("authoritative", Some("context"), 10)
            .unwrap()
            .iter()
            .any(|entry| entry.path == "CONTEXT.md"));
        assert!(store
            .search_project_history("initial", Some("context"), 10)
            .unwrap()
            .is_empty());
    }

    #[test]
    fn post_draft_history_refresh_rejects_an_index_from_another_repository() {
        let indexed = tempfile::tempdir().unwrap();
        let indexed_root = indexed.path();
        fs::write(
            indexed_root.join("CONTEXT.md"),
            "foreign source history marker\n",
        )
        .unwrap();
        let db = indexed_root.join("mmcg.db");
        let mut store = Store::open(&db).unwrap();
        Indexer::new(indexed_root)
            .index_all(&mut store, false)
            .unwrap();
        drop(store);

        let target = tempfile::tempdir().unwrap();
        fs::write(
            target.path().join("CONTEXT.md"),
            "target replacement history marker\n",
        )
        .unwrap();

        let error = refresh_project_history(target.path(), &db).unwrap_err();
        assert!(
            error.contains("index belongs to"),
            "unexpected error: {error}"
        );

        let store = Store::open(&db).unwrap();
        assert_eq!(
            store
                .search_project_history("foreign source", Some("context"), 10)
                .unwrap()
                .len(),
            1,
            "a rejected refresh must preserve the source repository history"
        );
        assert!(store
            .search_project_history("target replacement", Some("context"), 10)
            .unwrap()
            .is_empty());
    }

    #[cfg(unix)]
    #[test]
    fn context_writes_and_backups_reject_symlinks() {
        use std::os::unix::fs::symlink;

        let dir = tempfile::tempdir().unwrap();
        let outside = dir.path().join("outside.md");
        let context = dir.path().join("CONTEXT.md");
        fs::write(&outside, "do not overwrite\n").unwrap();
        symlink(&outside, &context).unwrap();

        assert!(write_if_absent(&context, "replacement\n", true).is_err());
        assert!(backup_existing(&context).is_err());
        assert_eq!(fs::read_to_string(outside).unwrap(), "do not overwrite\n");
    }
}
