use mmcg::audit_bundle::{read_envelope, verify_envelope, Envelope, VerifyPolicy};
use std::fmt::Write as _;
use std::path::Path;

const COMMENT_MAX: usize = 60 * 1024;
pub const COMMENT_MARKER: &str = "<!-- mastermind-verifiable-audit -->";

pub fn run(
    bundle_path: &Path,
    root: &Path,
    expected_repository: &str,
    expected_baseline: &str,
    expected_head: &str,
) -> Result<(), Box<dyn std::error::Error>> {
    let envelope = read_envelope(bundle_path)
        .map_err(|e| format!("sealed schema-v3 audit bundle required; regenerate it: {e}"))?;
    let report = verify_envelope(
        &envelope,
        &VerifyPolicy {
            expected_repository: Some(expected_repository.to_string()),
            expected_baseline: Some(expected_baseline.to_string()),
            expected_head: Some(expected_head.to_string()),
            root: Some(root.to_path_buf()),
            require_clean_worktree: true,
            ..VerifyPolicy::default()
        },
    );
    if !report.accepted() {
        return Err(format!(
            "audit bundle policy verification failed: {}",
            report.reasons.join(",")
        )
        .into());
    }
    print!("{}", render(&envelope, false)?);
    Ok(())
}

pub fn run_untrusted(bundle_path: &Path) -> Result<(), Box<dyn std::error::Error>> {
    let envelope = read_envelope(bundle_path)
        .map_err(|e| format!("sealed schema-v3 audit bundle required; regenerate it: {e}"))?;
    let report = verify_envelope(
        &envelope,
        &VerifyPolicy {
            integrity_only: true,
            ..VerifyPolicy::default()
        },
    );
    if report.content_integrity != "pass" {
        return Err("audit bundle content integrity failed".into());
    }
    print!("{}", render(&envelope, true)?);
    Ok(())
}

fn render(envelope: &Envelope, untrusted: bool) -> Result<String, Box<dyn std::error::Error>> {
    let manifest = &envelope.manifest;
    let verdict = safe(&manifest.verdict).to_uppercase();
    let icon = match verdict.as_str() {
        "HELD" => "✅",
        "DRIFT" => "⚠️",
        _ => "❌",
    };
    let mut out = String::new();
    writeln!(out, "{COMMENT_MARKER}")?;
    if untrusted {
        writeln!(out, "> ⚠️ UNTRUSTED INTEGRITY-ONLY RENDER — no repository, commit, or signer policy was evaluated.\n")?;
    }
    writeln!(out, "## {icon} Mastermind Audit — {verdict}\n")?;
    if !manifest.human_summary.is_empty() {
        writeln!(out, "> {}\n", safe(&manifest.human_summary))?;
    }
    writeln!(out, "**Spec:** `{}`  ", safe(&manifest.inputs.spec_path))?;
    writeln!(
        out,
        "**Baseline:** `{}` → **HEAD:** `{}`\n",
        safe(&manifest.repository.baseline_oid),
        safe(&manifest.repository.head_oid)
    )?;

    render_list(&mut out, "Failed claims", "❌", &manifest.failed_claims)?;
    render_list(&mut out, "Verified claims", "✅", &manifest.verified_claims)?;
    if !manifest.discrepancies.is_empty() {
        writeln!(
            out,
            "### Findings ({} total)\n",
            manifest.discrepancies.len()
        )?;
        for finding in &manifest.discrepancies {
            let kind = finding
                .get("kind")
                .and_then(serde_json::Value::as_str)
                .unwrap_or("unknown");
            writeln!(out, "- ⚠️ `{}`", safe(kind))?;
        }
        writeln!(out)?;
    }
    render_list(&mut out, "Declared files", "-", &manifest.declared_files)?;
    render_list(&mut out, "Changed files", "-", &manifest.changed_files)?;
    render_list(
        &mut out,
        "Mechanical mmcg queries",
        "-",
        &manifest.mmcg_queries,
    )?;
    render_list(
        &mut out,
        "Verify commands (recorded, never executed by publication)",
        "-",
        &manifest.verify_commands,
    )?;
    writeln!(
        out,
        "---\n*Generated by Mastermind — schema-v3 verifiable mechanical audit*"
    )?;
    if out.len() > COMMENT_MAX {
        return Err("rendered audit comment exceeds 60 KiB".into());
    }
    Ok(out)
}

fn render_list(
    out: &mut String,
    title: &str,
    icon: &str,
    values: &[String],
) -> Result<(), std::fmt::Error> {
    if values.is_empty() {
        return Ok(());
    }
    writeln!(out, "### {title}\n")?;
    for value in values {
        writeln!(out, "- {icon} `{}`", safe(value))?;
    }
    writeln!(out)
}

fn safe(value: &str) -> String {
    let mut output = String::with_capacity(value.len());
    for character in value.chars().take(4096) {
        match character {
            '@' => output.push_str("@\u{200b}"),
            '<' => output.push_str("&lt;"),
            '>' => output.push_str("&gt;"),
            '&' => output.push_str("&amp;"),
            '`' => output.push_str("\\`"),
            '*' | '_' | '[' | ']' | '(' | ')' | '#' | '!' | '|' | '~' | '\\' => {
                output.push('\\');
                output.push(character);
            }
            '\n' | '\r' | '\t' => output.push(' '),
            c if c.is_control() => output.push('�'),
            c => output.push(c),
        }
    }
    output
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn markdown_html_mentions_and_controls_are_neutralized() {
        let rendered = safe("@team <script> **x**\n\0");
        assert!(!rendered.contains("<script>"));
        assert!(!rendered.contains("@team"));
        assert!(!rendered.contains('\n'));
        assert!(!rendered.contains('\0'));
    }
}
